# Define paths
INCLUDE_PATH = /usr/local/include
LIB_PATH = /usr/local/lib

# Compiler and linker flags
CFLAGS = -Wall -Wextra -std=c11 -I$(INCLUDE_PATH)
LDFLAGS = -L$(LIB_PATH) -lraylib -lGL -lm -lpthread -ldl -lrt -lX11

# Targets and rules
all: connect4

connect4: src/main.o
    gcc $(CFLAGS) -o connect4 src/main.o $(LDFLAGS)

src/main.o: src/main.c
    gcc $(CFLAGS) -c src/main.c -o src/main.o

clean:
    rm -f src/*.o connect4
