name: Build and Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Raylib
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake git
        git clone https://github.com/raysan5/raylib.git
        cd raylib
        mkdir build
        cd build
        cmake ..
        make
        sudo make install
        cd ../..

    - name: Build
      run: make

    - name: Run tests
      run: make test
